name: Publish to NPM

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: |
          pnpm build

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm publish --provenance --access public --no-git-checks
